title: "Patrick Hurley's blog"
description: "Learnings, experiments, and research notes."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

excerpt_separator: "<!--end-preview-->"

minima:
  skin: auto
  
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - _drafts