title: "Patrick Hurley blog"
description: "Learnings, experiments, and research notes."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  skin: auto
  
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post_index.json

exclude:
  - README.md
  - _drafts